version: "3.3"

services:
    backend:
        image: ${BACKEND}
        ports:
            - "7110:80"
        depends_on:
            - db
            - cache
        restart: always
        volumes:
            - ./logs:/home/belli/logs
            - ./static:/home/belli/static
            - ./config.json:/home/belli/config.json
            - ./errorprotocol.json:/home/belli/errorprotocol.json
            - ./.env.local:/home/belli/.env

        environment:
            - LISTEN_ADDR=127.0.0.1:8080
            - DB_HOST=db
            - DB_PORT=5432
            - DB_USER=onki
            - DB_PASSWORD=onki
            - DB_DATABASE=onki
            - REDIS_HOST=cache
            - REDIS_PORT=6379
            - REDIS_DB=0
            - RENDERER_URL=http://renderer:5000

    renderer:
        image: ${RENDERER}
        restart: always
        environment:
            - HOST=0.0.0.0
            - PORT=5000
            - REMOTE_STATIC_HOST=http://backend
            - REMOTE_STATIC_PREFIX=static
            - CHROMIUM_PATH=/usr/bin/chromium-browser

    db:
        image: postgres:12-alpine
        restart: always
        environment:
            - POSTGRES_USER=onki
            - POSTGRES_PASSWORD=onki
            - POSTGRES_DB=onki
        volumes:
            - db_data:/var/lib/postgresql/data
            - ./postgres/init:/docker-entrypoint-initdb.d

    cache:
        image: redis:alpine
        restart: always
        volumes:
            - cache_data:/data
        command: redis-server --appendonly yes
volumes:
    db_data:
    cache_data: